App_View/Areas/Admin/Controllers/CartDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Data.Models;
using App_View.IServices;
using App_View.Services;

namespace App_View.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CartDetailsController : Controller
    {
        ICartDetailService _iCartDetailService;
        IUserService _iUserService;
        private readonly IProductDetailService iProductDetailService;

        public CartDetailsController(IProductDetailService _iProductDetailService)
        {
            _iCartDetailService = new CartDetailService();
            _iUserService = new UserService();
            iProductDetailService = _iProductDetailService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.CartDetail = await _iCartDetailService.GetCartDetailsAsync();
            ViewBag.ProductDetail = await iProductDetailService.GetListProductViewModelAsync();
            ViewBag.User = await _iUserService.GetUsersAsync();
            return View();
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "Id", "NameProduct");
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CartDetails obj)
        {
            var result = await _iCartDetailService.CreateCartDetailAsync(obj);
            if (result) return RedirectToAction("Index");
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "Id", "NameProduct");
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten");
            return View();
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _iCartDetailService.GetCartDetailByIdAsync(id);
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "Id", "NameProduct",result.IDCTSP);
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten",result.IDUser);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CartDetails obj)
        {
            var result = await _iCartDetailService.EditCartDetailAsync(obj);
            if (result) return RedirectToAction("Index");
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "ID", "NameProduct", obj.IDCTSP);
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten", obj.IDUser);
            return View();
        }
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _iCartDetailService.GetCartDetailByIdAsync(id);
            return View(result);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _iCartDetailService.DeleteCartDetailAsync(id);
            if (result) return RedirectToAction("Index");
            return View();
        }
    }
}

App_View/Controllers/CartDetailController.cs
using App_Data.IRepositories;
using App_Data.Models;
using App_Data.Repositories;
using App_Data.ViewModel;
using App_View.IServices;
using App_View.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Net.WebSockets;

namespace App_View.Controllers
{
    public class CartDetailController : Controller
    {
        private readonly IAllRepo<Cart> repos;
        DbContextModel dbContextModel = new DbContextModel();
        DbSet<Cart> Carts;
        CartService cartServices;
        CartDetailService cartDetailServices;
        UserService userServices;

        private IProductDetailService _productDetailService;

        public CartDetailController(IProductDetailService productDetailService)
        {
            Carts = dbContextModel.Carts;
            AllRepo<Cart> all = new AllRepo<Cart>(dbContextModel, Carts);
            repos = all;
            cartServices = new CartService();
            cartDetailServices = new CartDetailService();
            userServices = new UserService();
            _productDetailService = productDetailService;
        }
        public async Task<ActionResult> ShowAllCartDetail()
        {
            var cart = await cartDetailServices.GetCartDetailsAsync();
            return View(cart);
        }
        public async Task<ActionResult> ShowCart()
        {
            var acc = SessionService.GetUserFromSession(HttpContext.Session, "SaveLoginUser").Id;
            var idCart = (await userServices.GetUserByIdAsync(acc)).Id;
            var a = (await cartDetailServices.GetCartDetailsAsync()).Where(c => c.IdUser == acc).ToList();
            return View(a);
        }

        public async Task<ActionResult> CheckOut()
        {
            var acc = SessionService.GetUserFromSession(HttpContext.Session, "SaveLoginUser").Id;
            var a = (await cartDetailServices.GetCartDetailsAsync()).Where(c => c.IdUser == acc).ToList();
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCartUser([FromBody]CartViewModel model)
        {
            var acc = SessionService.GetUserFromSession(HttpContext.Session, "SaveLoginUser").Id;
            var product = await _productDetailService.GetProductDTOByIdAsync(model.IdProduct);
            //if (acc == null)
            //{

            //    TempData["dangnhap"] = "Bạn phải đăng nhập";
            //}
            //else
            //{

            var IdCart = (await userServices.GetUsersAsync()).FirstOrDefault(c => c.Id == acc).Id;
            var existing = (await cartDetailServices.GetCartDetailsAsync()).FirstOrDefault(x => x.IdProduct == product.Id && x.IdUser == IdCart);
            if (existing != null)
            {
                //Kiểm tra số lượng vs số lượng tồn
                if (existing.SoLuongCart + model.SoLuongCart <= product.SoLuongTon)
                {
                    // Nếu sản phẩm đã có trong giỏ hàng thì tăng số lượng lên 1
                    existing.SoLuongCart += model.SoLuongCart;
                }
                else
                {
                    TempData["quantityCartUser"] = "Số lượng bạn chọn đã đạt mức tối đa của sản phẩm này";
                    existing.SoLuongCart = Convert.ToInt32(product.SoLuongTon);
                }
                var cartdetail = new CartDetails()
                {
                    ID = existing.Id,
                    IDCTSP = product.Id,
                    IDUser = IdCart,
                    GiaKhuyenMai = Convert.ToDecimal(existing.GiaBan),
                    SoLuong = existing.SoLuongCart,
                };
                cartDetailServices.EditCartDetailAsync(cartdetail);
            }
            else
            {
                var cartDetails = new CartDetails();
                cartDetails.IDUser = IdCart;
                cartDetails.IDCTSP = model.IdProduct;
                cartDetails.SoLuong = model.SoLuongCart;
                cartDetails.GiaKhuyenMai = Convert.ToDecimal(product.GiaBan);
                cartDetails.TrangThai = 0;
                cartDetailServices.CreateCartDetailAsync(cartDetails);
            }

            //}
            return RedirectToAction("ShowCart");

        }


        public async Task<IActionResult> DetailCartDetail(Guid id)
        {
            var cart = repos.GetAll().FirstOrDefault(c => c.IdUser == id);
            return View(cart);
        }
        public async Task<IActionResult> DeleteCartDetail(Guid id)
        {
            var result = await cartDetailServices.DeleteCartDetailAsync(id);
            if (result) return RedirectToAction("ShowCart");
            return RedirectToAction("ShowCart");
        }
        public async Task<IActionResult> CapNhatSoLuongGioHang(Guid idCart, int SoLuong, Guid IdProduct)
        {
            var apiUrl = $"https://localhost:7165/api/CartDetail/Update-cart?id={idCart}&soLuongCart={SoLuong}";
            var httpClient = new HttpClient();
            var response = await httpClient.PutAsync(apiUrl, null);
            var price = Convert.ToDecimal((await _productDetailService.GetProductDTOByIdAsync(IdProduct)).GiaBan * SoLuong);
            var tonggia = string.Format(CultureInfo.GetCultureInfo("vi-VN"), "{0:N0}đ", price);
            //var acc = SessionServices.GetObjFromSession(HttpContext.Session, "acc").TaiKhoan;
            var giohang = (await cartDetailServices.GetCartDetailsAsync()).Where(c => c.IdUser == Guid.Parse("36668394-764E-71F5-D3BE-278C8C20C8A1")).ToList();
            decimal? TongTien = 0;
            foreach (var item in giohang)
            {
                TongTien += item.GiaBan * Convert.ToDecimal(item.SoLuongCart);
            }
            return Json(new { TongTien = TongTien, TongGia = tonggia });

        }
    }
}

App_View/Areas/Admin/Views/CartDetails/Create.cshtml
@model App_Data.Models.CartDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="IDUser" class="control-label">Khách Hàng</label>
                <select asp-for="IDUser" class="form-control" asp-items="@ViewBag.User"></select>
                <span asp-validation-for="IDUser" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="IDCTSP" for="inputPassword4">Sản Phẩm</label>
                 <select asp-for="IDCTSP" class ="form-control" asp-items="@ViewBag.ProductDetail"></select>
                <span asp-validation-for="IDCTSP" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputCity" asp-for="GiaKhuyenMai">Giá Khuyến Mãi</label>
                <input type="number" class="form-control" asp-for="GiaKhuyenMai" id="inputCity">
                <span asp-validation-for="GiaKhuyenMai" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label for="inputState" asp-for="SoLuong">Số Lượng</label>
                <input type="number" class="form-control" asp-for="SoLuong" id="inputState">
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group col-md-2">
                <label for="inputCity" asp-for="TrangThai">Trạng Thái</label>
                <input type="number" class="form-control" asp-for="TrangThai" id="inputCity">
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Thêm</button>
    </form>
    <div>
        <a asp-action="Index" asp-controller="CartDetails" asp-area="Admin">Trở Về</a>
    </div>

    @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

App_View/Areas/Admin/Views/CartDetails/Details.cshtml
@model App_Data.Models.CartDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>CartDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GiaKhuyenMai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaKhuyenMai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cart.IdUser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDetail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductDetail.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

App_View/Areas/Admin/Views/CartDetails/Edit.cshtml
@model App_Data.Models.CartDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="IDUser" class="control-label">Khách Hàng</label>
            <select asp-for="IDUser" class="form-control" asp-items="@ViewBag.User"></select>
            <span asp-validation-for="IDUser" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="IDCTSP" for="inputPassword4">Sản Phẩm</label>
            <select asp-for="IDCTSP" class="form-control" asp-items="@ViewBag.ProductDetail"></select>
            <span asp-validation-for="IDCTSP" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputCity" asp-for="GiaKhuyenMai">Giá Khuyến Mãi</label>
            <input type="number" class="form-control" asp-for="GiaKhuyenMai" id="inputCity">
            <span asp-validation-for="GiaKhuyenMai" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label for="inputState" asp-for="SoLuong">Số Lượng</label>
            <input type="number" class="form-control" asp-for="SoLuong" id="inputState">
            <span asp-validation-for="SoLuong" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label for="inputCity" asp-for="TrangThai">Trạng Thái</label>
            <input type="number" class="form-control" asp-for="TrangThai" id="inputCity">
            <span asp-validation-for="TrangThai" class="text-danger"></span>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Sửa</button>
</form>
<div>
    <a asp-action="Index" asp-controller="CartDetails" asp-area="Admin">Trở Về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

App_View/Areas/Admin/Views/CartDetails/Index.cshtml
@using App_Data.Models
@using App_Data.ViewModels
@using App_Data.ViewModels.ProductDetail

@model IEnumerable<App_Data.Models.CartDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<CartDetails> cartDetails = ViewBag.CartDetail;
    IEnumerable<ProductViewModel> productDetail = ViewBag.ProductDetail;
    List<User> users = ViewBag.User;
}
<link href="~/Admin_assets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
<script src="~/Admin_assets/vendors/datatables/jquery.dataTables.min.js"></script>
<script src="~/Admin_assets/vendors/datatables/dataTables.bootstrap.min.js"></script>
<a asp-controller="CartDetails" asp-area="Admin" asp-action="Create" class="btn btn-info" style="margin-bottom: 30px;">Thêm</a>
<table id="data-table" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaKhuyenMai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDetail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in cartDetails)
        {
            <tr>
                <td>
                    @(item.SoLuong)
                </td>
                <td>
                    @(item.GiaKhuyenMai)
                </td>
                <td>
                    @(item.TrangThai)
                </td>

                <td>
                    @(users.FirstOrDefault(c => c.Id == item.IDUser).Ten)
                </td>
                <td>
                    @(productDetail.FirstOrDefault(c => c.Id == item.IDCTSP).NameProduct)
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="CartDetails" asp-area="Admin" asp-route-id="@item.ID" class="btn btn-warning"><i class="anticon anticon-edit"></i></a>
                    <a asp-action="Details" asp-controller="CartDetails" asp-area="Admin" asp-route-id="@item.ID" class="btn btn-info"><i class="anticon anticon-eye"></i></a>
                    <a asp-action="Delete" asp-controller="CartDetails" asp-area="Admin" asp-route-id="@item.ID" class="btn btn-danger"><i class="anticon anticon-delete"></i></a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaKhuyenMai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDetail)
            </th>
            <th></th>
        </tr>
    </tfoot>
</table>
<script>
	$('#data-table').DataTable();
</script>