App_View/Areas/Admin/Controllers/ProductDetailsController.cs
using App_Data.Models;
using App_Data.ViewModels.ProductDetail;
using App_View.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace App_View.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductDetailsController : Controller
    {
        private readonly IProductDetailService _productDetailService;
        private readonly DbContextModel _context;

        public ProductDetailsController(IProductDetailService productDetailService)
        {
            _productDetailService = productDetailService;
            _context = new DbContextModel();
        }

        [HttpPost]
        public async Task<IActionResult> CheckProductDetailForAddOrUpdate([FromBody] ProductDetailDTO productDetailDTO)
        {
            var response = await _productDetailService.GetProductDetailForUpdateOrAdd(productDetailDTO);
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                return Content(content, "application/json");

            }
            return BadRequest();
        }

        //GET: Admin/ProductDetails
        public IActionResult Index()
        {
            return View();
        }

        //GET: Admin/ProductDetails
        public IActionResult DanhSachSanPhamNgungKinhDoanh()
        {
            return View();
        }


        public async Task<IActionResult> LoadPartialViewChiTietSanPham(Guid id)
        {
            return PartialView("_DetailPartialView", await _productDetailService.GetProductVMsAsync(id));
        }

        public class ListGuidDTO
        {
            public List<Guid>? LstGuid { get; set; }
        }

        [HttpPost]
        public async Task<IActionResult> LoadPartialviewDanhSachUpdate([FromBody] ListGuidDTO listGuidDTO)
        {
            var model = (await _productDetailService.GetListProductViewModelAsync())!
                .Where(sp => listGuidDTO.LstGuid!.Contains(sp.Id));
            return PartialView("_DanhSachSanPhamUpdate", model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateNgungKinhDoanhForList([FromBody] ListGuidDTO listGuidDTO)
        {
            foreach (var IdProduct in listGuidDTO.LstGuid!)
            {
                var productGet = _context.ProductDetails.FirstOrDefault(pro => pro.Id == IdProduct);
                productGet!.TrangThai = 1;
                _context.ProductDetails.Update(productGet);
                await _context.SaveChangesAsync();
            }
            return Ok();
        }

        #region AddNameProduct
        public class ProductDTO
        {
            public string? nameProduct { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> CreateNameProduct([FromBody] ProductDTO productDTO)
        {
            if (!string.IsNullOrEmpty(productDTO.nameProduct))
            {
                return Ok(await _productDetailService.CreateProductAsynsc(productDTO.nameProduct));
            }
            return BadRequest();
        }
        #endregion

        #region AddNameTypeProduct
        public class TypeProductDTO
        {
            public string? nameTypeProduct { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> CreateNameTypeProduct([FromBody] TypeProductDTO typeProducttDTO)
        {
            if (!string.IsNullOrEmpty(typeProducttDTO.nameTypeProduct))
            {
                try
                {
                    var typeProduct = new TypeProduct()
                    {
                        Id = Guid.NewGuid(),
                        Ma = "TY" + (_context.TypeProducts.ToList().Count + 1),
                        Ten = typeProducttDTO.nameTypeProduct,
                        TrangThai = 0
                    };
                    await _context.TypeProducts.AddAsync(typeProduct);
                    await _context.SaveChangesAsync();
                    return Ok(new { id = typeProduct.Id, name = typeProduct.Ten });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    return BadRequest();
                }

            }
            return BadRequest();
        }
        #endregion

        #region AddNameMaterial
        public class MaterialDTO
        {
            public string? nameMaterial { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> CreateNameMaterial([FromBody] MaterialDTO materialDTO)
        {
            if (!string.IsNullOrEmpty(materialDTO.nameMaterial))
            {
                try
                {
                    var material = new Material()
                    {
                        Id = Guid.NewGuid(),
                        Ten = materialDTO.nameMaterial,
                        TrangThai = 0
                    };
                    await _context.Materials.AddAsync(material);
                    await _context.SaveChangesAsync();
                    return Ok(new { id = material.Id, name = material.Ten });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    return BadRequest();
                }

            }
            return BadRequest();
        }
        #endregion

        #region AddNameColor
        public class ColorDTO
        {
            public string? nameColor { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> CreateNameColor([FromBody] ColorDTO colorDTO)
        {
            if (!string.IsNullOrEmpty(colorDTO.nameColor))
            {
                try
                {
                    var color = new App_Data.Models.Color()
                    {
                        Id = Guid.NewGuid(),
                        Ten = colorDTO.nameColor,
                        Ma = "MS" + (_context.TypeProducts.ToList().Count + 1),
                        TrangThai = 0
                    };
                    await _context.Colors.AddAsync(color);
                    await _context.SaveChangesAsync();
                    return Ok(new { id = color.Id, name = color.Ten });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    return BadRequest();
                }

            }
            return BadRequest();
        }
        #endregion

        #region AddNameSize
        public class SizeDTO
        {
            public string? nameSize { get; set; }
        }
        [HttpPost]
        public async Task<IActionResult> CreateNameSize([FromBody] SizeDTO sizeDTO)
        {
            if (!string.IsNullOrEmpty(sizeDTO.nameSize))
            {
                try
                {
                    var size = new App_Data.Models.Size()
                    {
                        Id = Guid.NewGuid(),
                        Size1 = sizeDTO.nameSize,
                        Ma = "Siz" + (_context.Sizes.ToList().Count + 1),
                        Cm = 1,
                        TrangThai = 0
                    };
                    await _context.Sizes.AddAsync(size);
                    await _context.SaveChangesAsync();
                    return Ok(new { id = size.Id, name = size.Size1 });
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    return BadRequest();
                }

            }
            return BadRequest();
        }
        #endregion


        public async Task<IActionResult> ViewAddSale()
        {
            ViewData["IdSale"] = new SelectList(_context.Sales, "Id", "Ten");
            return View();
        }

        public IActionResult ManageProduct()
        {
            ViewData["IdColor"] = new SelectList(_context.Colors, "Id", "Ten");
            ViewData["IdMaterial"] = new SelectList(_context.Materials, "Id", "Ten");
            ViewData["IdProduct"] = new SelectList(_context.Products, "Id", "Ten");
            ViewData["IdSize"] = new SelectList(_context.Sizes, "Id", "Size1");
            ViewData["IdTypeProduct"] = new SelectList(_context.TypeProducts, "Id", "Ten");
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetProducts(int draw, int start, int length, string searchValue)
        {
            var query = (await _productDetailService.GetListProductViewModelAsync())!
                .Skip(start)
                .Take(length)
                .ToList();

            if (!string.IsNullOrEmpty(searchValue))
            {
                string searchValueLower = searchValue.ToLower();
                query = (await _productDetailService.GetListProductViewModelAsync())!.Where(x => x.NameProduct!.ToLower().Contains(searchValueLower) || x.Loai!.ToLower().Contains(searchValueLower) || x.ChatLieu!.ToLower().Contains(searchValueLower) || x.MauSac!.ToLower().Contains(searchValueLower))
                .Skip(start)
                .Take(length)
                .ToList();

            }

            var totalRecords = (await _productDetailService.GetListProductViewModelAsync())!.Count();

            return Json(new
            {
                draw = draw,
                recordsTotal = totalRecords,
                recordsFiltered = totalRecords,
                data = query
            });
        }
        #region ViewSanPhamNgungKinhDoanh

        [HttpGet]
        public async Task<IActionResult> GetProductsNgungKinhDoanh(int draw, int start, int length, string searchValue)
        {
            var query = (await _productDetailService.GetLstProductDetailViewModelNgungKinhDoanhAynsc())!
                .Skip(start)
                .Take(length)
                .ToList();

App_View/Areas/Admin/Views/ProductDetails/DanhSachSanPhamNgungKinhDoanh.cshtml
@model IEnumerable<App_Data.ViewModels.ProductDetail.ProductViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .clickable-image {
        cursor: pointer
    }

    tr {
        margin-top: 2px;
    }
</style>
<div id="body_parent">
    <div id="modal"></div>
    <div class="modal fade" id="modalSanPham"></div>
    <div class="notification-toast top-right" id="notification-toast"></div>
    <div class="card">
        <div class="card-body">
            <div class="row m-b-30">
                <div class="col-lg-8">
                    <div class="d-md-flex">

                    </div>
                </div>
                <div class="col-lg-4 text-right">
                    <button class="btn btn-primary" onclick="window.location.href = '/Admin/ProductDetails'">
                        <i class="anticon anticon-arrow-left m-r-5"></i>
                        <span>Quay lại danh sánh</span>
                    </button>
                </div>
            </div>
            <table id="tabe_ViewProduct" class="table" style="width:100%!important">
                <thead>
                    <tr>
                        <th>
                            <div class="checkbox">
                                <input id="check-all" type="checkbox">
                                <label for="check-all"></label>
                            </div>
                        </th>
                        <th style="width:6px">STT</th>
                        <th>Tên</th>
                        <th>Màu Sắc</th>
                        <th>Size</th>
                        <th>Loại</th>
                        <th>Chất liệu</th>
                        <th>Số Lượng</th>
                        <th>Giá bán</th>
                        <th>Trạng thái</th>
                        <th>###</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

</div>
<script>
    var selectedCheckboxes = {};
    var table;
    $(document).ready(function () {
        table =
        $('#tabe_ViewProduct').DataTable({
        ajax: {
            url: '@Url.Action("GetProductsNgungKinhDoanh", "ProductDetails", new { area = "Admin" })',
            type: 'GET',
            dataType: 'json',
            data: function (d) {
                return {
                    draw: d.draw,
                    start: d.start,
                    length: d.length,
                    searchValue: d.search.value
                };
            },
            cache: false
        },
        serverSide: true,
        paging: true,
        columns: [
            {
                data: "id",
                render: function (data, type, full, meta) {
                    const isChecked = selectedCheckboxes[data.idChiTietSp];
                    const checkedAttribute = isChecked ? 'checked' : '';
                    return `
                        <td>
                            <div class="checkbox" data-id="${data}">
                                <input id="check-item-${data}" class="for_check_box" type="checkbox" "${checkedAttribute}">
                                <label for="check-item-${data}" class="m-b-0"></label>
                            </div>
                        </td>
                    `;
                }
            },
            {
                data: null,
                render: function (data, type, full, meta) {
                    return meta.row + 1;
                }
            },
            {
                data: null,
                render: function (data, type, full, meta) {
                    if (data && data.lstTenAnh && data.lstTenAnh.length > 0 && data.nameProduct) {
                        return `
                            <td>
                                <div class="d-flex align-items-center">
                                    <img class="img-fluid rounded clickable-image" src="/images/anhsanpham/${data.lstTenAnh[0]}" style="max-width: 60px" alt="" data-rowdata='${data.id}'>
                                    <h6 class="m-b-0 m-l-10">${data.nameProduct}</h6>
                                </div>
                            </td>
                        `;
                    } else {
                        return `
                            <td>
                                <div class="d-flex align-items-center">
                                    <img class="img-fluid rounded clickable-image" src="/Admin_assets/images/others/login-3.png" style="max-width: 60px" alt="" data-rowdata='${data.id}'>
                                    <h6 class="m-b-0 m-l-10">${data.nameProduct}</h6>
                                </div>
                            </td>
                        `;
                    }
                }
            },
            {
                data: 'mauSac'
            },
            {
                data: 'size'
            },
            {
                data: 'loai'
            },
            {
                data: 'chatLieu'
            },
            {
                data: 'soLuongTon'
            },
            {
                data: 'giaBan',
                render: function (data, type, full, meta) {
                    if (type === 'display' || type === 'filter') {
                        var formattedPrice = new Intl.NumberFormat('vi-VN', {
                            style: 'currency',
                            currency: 'VND'
                        }).format(data).replace(",00", "");

                        return formattedPrice;
                    } else {
                        return data;
                    }
                }
            },
            {
                data: null,
                render: function (data, type, full, meta) {
                    if (data && data.trangThai == 0) {
                        return `
                        <div class="trangThai">
                            <td>
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                    <div>Active</div>
                                </div>
                            </td>
                        </div>
                        `;
                    } else {
                        return `
                        <div class="trangThai">
                            <td>
                                <div class="d-flex align-items-center">
                                    <div class="badge badge-danger badge-dot m-r-10"></div>
                                    <div>No Active</div>
                                </div>
                            </td>
                        </div>
                        `;
                    }
                }
            },
            {
                data: null,
                render: function (data, type, full, meta) {
                    const iddata = data.id
                    return `<td class="text-right">
                        <button class="btn btn-icon btn-hover btn-sm btn-rounded khoi_phuc" data-id="${iddata}">
                            <i class="fas fa-undo-alt"></i>
                        </button>
                    </td>`;
                }
            },
        ],
            initComplete: function (settings, json) {
            $('#tabe_ViewProduct').on('draw.dt', function () {
                $('.for_check_box').each(function () {
                    const id = $(this).attr('id').replace('check-item-', '');
                    if (selectedCheckboxes[id]) {
                        $(this).prop('checked', true);
                    } else {
                        $(this).prop('checked', false);
                    }
                });
            });

            $('#check-all').on('change', function () {
                const isCheckedAll = $(this).prop('checked');
                    $('input[type="checkbox"].for_check_box').each(function () {
                        const id = $(this).attr('id').replace('check-item-', '');

                        $(this).prop('checked', isCheckedAll);
                        if (isCheckedAll) {
                            selectedCheckboxes[id] = true;
                        } else {
                            delete selectedCheckboxes[id];
                        }
                    //checkToshowConfirm();
                });
            });

            $('#tabe_ViewProduct').on('change', 'input[type="checkbox"]', function () {
                const id = $(this).attr('id').replace('check-item-', '');
                if ($(this).prop('checked')) {
                    selectedCheckboxes[id] = true;
                } else {
                    delete selectedCheckboxes[id];
                }

                const totalCheckboxes = $('#tabe_ViewProduct').find('input[type="checkbox"]').length;
                const totalChecked = $('#tabe_ViewProduct').find('input[type="checkbox"]:checked').length;

                console.log(totalCheckboxes);
                console.log(totalChecked);

                $('#check-all').prop('checked', totalChecked === totalCheckboxes);
                //checkToshowConfirm();
            });
        }
    });
   });
    $(document).on('click', '.clickable-image', function () {
        var rowData = $(this).data('rowdata');
        showProductDetail(rowData);
    })

    function showProductDetail(rowData) {
        $.ajax({
            url: '/Admin/ProductDetails/LoadPartialViewChiTietSanPham?id=' + rowData,
            type: 'GET',
            success: function (result) {
                const modal = $('#modalSanPham');
                modal.empty();
                modal.html(result);
                modal.modal("show")
            },
            error: function (xhr, status, error) {
                console.log(xhr.responseText);
                console.log(status);
                console.log(error);
                console.log(xhr);
            }
        });

    }

    $('#tabe_ViewProduct').on('click', '.khoi_phuc', function () {
    const item = $(this)
    const id = $(this).data('id');
        const UrlDelete = '@Url.Action("KhoiPhucKinhDoanh", "ProductDetails", new { area = "Admin" })';

        $.ajax({
            url: UrlDelete,
            type: 'GET',
            data: {
                'IdSanPham': id
            },
            success: function (result) {
                item.closest("tr").remove()
                delete selectedCheckboxes[id];
                $('#confirm').modal('hide');
                showToastDeleteSucsess();
                table.draw();
            },
            error: function (xhr, status, error) {
                console.log(xhr.responseText);
                console.log(status);
                console.log(error);
                console.log(xhr);
            }
        });
    })

    function showToastDeleteSucsess() {
        var toastHTML = `<div class="toast fade hide" data-delay="3000">
                            <div class="toast-header">
                                <i class="anticon anticon-info-circle text-primary m-r-5"></i>
                                <strong class="mr-auto">Thông báo</strong>
                                <small>1 seconds ago</small>
                                <button type="button" class="ml-2 close" data-dismiss="toast" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="toast-body">
                                <span>Đã khôi phục kinh doanh một mặt hàng!</span>
                            </div>
                        </div>`

        $('#notification-toast').append(toastHTML)
        $('#notification-toast .toast').toast('show');
        setTimeout(function () {
            $('#notification-toast .toast:first-child').remove();
        }, 3000);
    }
    $(document).on('click', '#update', function () {
        const keys = Object.keys(selectedCheckboxes).filter(item => item !== "check-all");
        console.log(keys);
        const container = $("#body_parent").empty();

        var dataGet = {
            LstGuid: keys,
        };
        $.ajax({
            url: '/Admin/ProductDetails/LoadPartialviewDanhSachUpdate',
            type: 'Post',
            data: JSON.stringify(dataGet),
            contentType: 'application/json',
            success: function (result) {
                container.append(result);
            },
            error: function (xhr, status, error) {
                console.log(xhr.responseText);
                console.log(status);
                console.log(error);
                console.log(xhr);
            }
        });

    })
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/Admin_assets/js/pages/e-commerce-order-list.js"></script>
    <script src="~/Admin_assets/vendors/datatables/jquery.dataTables.min.js" defer></script>
    <script src="~/Admin_assets/vendors/datatables/dataTables.bootstrap.min.js" defer></script>
    <script src="~/Admin_assets/js/pages/datatables.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autonumeric/4.8.1/autoNumeric.min.js"></script>
}

App_View/Areas/Admin/Views/ProductDetails/ViewAddSale.cshtml
@model IEnumerable<App_Data.ViewModels.ProductDetail.ProductViewModel>

@{
    ViewData["Title"] = "ViewAddSale";
}

<h1>ViewAddSale</h1>
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="#" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>QUẢN LÝ SẢN PHẨM</a>
            <a class="breadcrumb-item" href="#">ADD SALE</a>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body" id="formGen">
        <div style="display: flex; align-items: center; justify-content: space-between;">
            <h5 style="margin: 0;">QUẢN LÝ SẢN PHẨM</h5>
            <button onclick="generate()" class="btn btn-warning">Tạo thực thể</button>
        </div>
        <div class="m-b-15" style="margin-bottom: 30px">
            <div class="row">
                <div class="col-4" style="margin-top: 10px">
                    <label>NameProduct</label>
                    <select id="IdSale" class="select2" name="IdSale">
                        @foreach (var item in (SelectList)ViewData["IdSale"])
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>