App_View/Areas/Admin/Controllers/CartDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App_Data.Models;
using App_View.IServices;
using App_View.Services;

namespace App_View.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CartDetailsController : Controller
    {
        ICartDetailService _iCartDetailService;
        IUserService _iUserService;
        private readonly IProductDetailService iProductDetailService;

        public CartDetailsController(IProductDetailService _iProductDetailService)
        {
            _iCartDetailService = new CartDetailService();
            _iUserService = new UserService();
            iProductDetailService = _iProductDetailService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.CartDetail = await _iCartDetailService.GetCartDetailsAsync();
            ViewBag.ProductDetail = await iProductDetailService.GetListProductViewModelAsync();
            ViewBag.User = await _iUserService.GetUsersAsync();
            return View();
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "Id", "NameProduct");
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CartDetails obj)
        {
            var result = await _iCartDetailService.CreateCartDetailAsync(obj);
            if (result) return RedirectToAction("Index");
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "Id", "NameProduct");
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten");
            return View();
        }
        public async Task<IActionResult> Edit(Guid id)
        {
            var result = await _iCartDetailService.GetCartDetailByIdAsync(id);
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "Id", "NameProduct",result.IDCTSP);
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten",result.IDUser);
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CartDetails obj)
        {
            var result = await _iCartDetailService.EditCartDetailAsync(obj);
            if (result) return RedirectToAction("Index");
            ViewBag.ProductDetail = new SelectList(await iProductDetailService.GetListProductViewModelAsync(), "ID", "NameProduct", obj.IDCTSP);
            ViewBag.User = new SelectList(await _iUserService.GetUsersAsync(), "Id", "Ten", obj.IDUser);
            return View();
        }
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _iCartDetailService.GetCartDetailByIdAsync(id);
            return View(result);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _iCartDetailService.DeleteCartDetailAsync(id);
            if (result) return RedirectToAction("Index");
            return View();
        }
    }
}

App_View/Controllers/CartDetailController.cs
using App_Data.IRepositories;
using App_Data.Models;
using App_Data.Repositories;
using App_Data.ViewModel;
using App_View.IServices;
using App_View.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Net.WebSockets;

namespace App_View.Controllers
{
    public class CartDetailController : Controller
    {
        private readonly IAllRepo<Cart> repos;
        DbContextModel dbContextModel = new DbContextModel();
        DbSet<Cart> Carts;
        CartService cartServices;
        CartDetailService cartDetailServices;
        UserService userServices;

        private IProductDetailService _productDetailService;

        public CartDetailController(IProductDetailService productDetailService)
        {
            Carts = dbContextModel.Carts;
            AllRepo<Cart> all = new AllRepo<Cart>(dbContextModel, Carts);
            repos = all;
            cartServices = new CartService();
            cartDetailServices = new CartDetailService();
            userServices = new UserService();
            _productDetailService = productDetailService;
        }
        public async Task<ActionResult> ShowAllCartDetail()
        {
            var cart = await cartDetailServices.GetCartDetailsAsync();
            return View(cart);
        }
        public async Task<ActionResult> ShowCart()
        {
            var acc = SessionService.GetUserFromSession(HttpContext.Session, "SaveLoginUser").Id;
            var idCart = (await userServices.GetUserByIdAsync(acc)).Id;
            var a = (await cartDetailServices.GetCartDetailsAsync()).Where(c => c.IdUser == acc).ToList();
            return View(a);
        }

        public async Task<ActionResult> CheckOut()
        {
            var acc = SessionService.GetUserFromSession(HttpContext.Session, "SaveLoginUser").Id;
            var a = (await cartDetailServices.GetCartDetailsAsync()).Where(c => c.IdUser == acc).ToList();
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCartUser([FromBody]CartViewModel model)
        {
            var acc = SessionService.GetUserFromSession(HttpContext.Session, "SaveLoginUser").Id;
            var product = await _productDetailService.GetProductDTOByIdAsync(model.IdProduct);
            //if (acc == null)
            //{

            //    TempData["dangnhap"] = "Bạn phải đăng nhập";
            //}
            //else
            //{

            var IdCart = (await userServices.GetUsersAsync()).FirstOrDefault(c => c.Id == acc).Id;
            var existing = (await cartDetailServices.GetCartDetailsAsync()).FirstOrDefault(x => x.IdProduct == product.Id && x.IdUser == IdCart);
            if (existing != null)
            {
                //Kiểm tra số lượng vs số lượng tồn
                if (existing.SoLuongCart + model.SoLuongCart <= product.SoLuongTon)
                {
                    // Nếu sản phẩm đã có trong giỏ hàng thì tăng số lượng lên 1
                    existing.SoLuongCart += model.SoLuongCart;
                }
                else
                {
                    TempData["quantityCartUser"] = "Số lượng bạn chọn đã đạt mức tối đa của sản phẩm này";
                    existing.SoLuongCart = Convert.ToInt32(product.SoLuongTon);
                }
                var cartdetail = new CartDetails()
                {
                    ID = existing.Id,
                    IDCTSP = product.Id,
                    IDUser = IdCart,
                    GiaKhuyenMai = Convert.ToDecimal(existing.GiaBan),
                    SoLuong = existing.SoLuongCart,
                };
                cartDetailServices.EditCartDetailAsync(cartdetail);
            }
            else
            {
                var cartDetails = new CartDetails();
                cartDetails.IDUser = IdCart;
                cartDetails.IDCTSP = model.IdProduct;
                cartDetails.SoLuong = model.SoLuongCart;
                cartDetails.GiaKhuyenMai = Convert.ToDecimal(product.GiaBan);
                cartDetails.TrangThai = 0;
                cartDetailServices.CreateCartDetailAsync(cartDetails);
            }

            //}
            return RedirectToAction("ShowCart");

        }


        public async Task<IActionResult> DetailCartDetail(Guid id)
        {
            var cart = repos.GetAll().FirstOrDefault(c => c.IdUser == id);
            return View(cart);
        }
        public async Task<IActionResult> DeleteCartDetail(Guid id)
        {
            var result = await cartDetailServices.DeleteCartDetailAsync(id);
            if (result) return RedirectToAction("ShowCart");
            return RedirectToAction("ShowCart");
        }
        public async Task<IActionResult> CapNhatSoLuongGioHang(Guid idCart, int SoLuong, Guid IdProduct)
        {
            var apiUrl = $"https://localhost:7165/api/CartDetail/Update-cart?id={idCart}&soLuongCart={SoLuong}";
            var httpClient = new HttpClient();
            var response = await httpClient.PutAsync(apiUrl, null);
            var price = Convert.ToDecimal((await _productDetailService.GetProductDTOByIdAsync(IdProduct)).GiaBan * SoLuong);
            var tonggia = string.Format(CultureInfo.GetCultureInfo("vi-VN"), "{0:N0}đ", price);
            //var acc = SessionServices.GetObjFromSession(HttpContext.Session, "acc").TaiKhoan;
            var giohang = (await cartDetailServices.GetCartDetailsAsync()).Where(c => c.IdUser == Guid.Parse("36668394-764E-71F5-D3BE-278C8C20C8A1")).ToList();
            decimal? TongTien = 0;
            foreach (var item in giohang)
            {
                TongTien += item.GiaBan * Convert.ToDecimal(item.SoLuongCart);
            }
            return Json(new { TongTien = TongTien, TongGia = tonggia });

        }
    }
}

App_View/Views/CartDetail/AddCartDetail.cshtml
@model App_Data.Models.CartDetails

@{
    ViewData["Title"] = "AddCartDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>AddCartDetail</h1>

<h4>CartDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCartDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IDUser" class="control-label"></label>
                <input asp-for="IDUser" class="form-control" />
                <span asp-validation-for="IDUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDCTSP" class="control-label"></label>
                <input asp-for="IDCTSP" class="form-control" />
                <span asp-validation-for="IDCTSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaKhuyenMai" class="control-label"></label>
                <input asp-for="GiaKhuyenMai" class="form-control" />
                <span asp-validation-for="GiaKhuyenMai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

App_View/Views/CartDetail/DetailCartDetail.cshtml
@model App_Data.Models.CartDetails

@{
    ViewData["Title"] = "DetailCartDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DetailCartDetail</h1>

<div>
    <h4>CartDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IDUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IDUser)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IDCTSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IDCTSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GiaKhuyenMai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GiaKhuyenMai)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrangThai)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

App_View/Views/CartDetail/EditCartDetail.cshtml
@model App_Data.Models.CartDetails

@{
    ViewData["Title"] = "EditCartDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditCartDetail</h1>

<h4>CartDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCartDetail">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IDUser" class="control-label"></label>
                <input asp-for="IDUser" class="form-control" />
                <span asp-validation-for="IDUser" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDCTSP" class="control-label"></label>
                <input asp-for="IDCTSP" class="form-control" />
                <span asp-validation-for="IDCTSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaKhuyenMai" class="control-label"></label>
                <input asp-for="GiaKhuyenMai" class="form-control" />
                <span asp-validation-for="GiaKhuyenMai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TrangThai" class="control-label"></label>
                <input asp-for="TrangThai" class="form-control" />
                <span asp-validation-for="TrangThai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

App_View/Views/CartDetail/ShowAllCartDetail.cshtml
@using App_Data.Models
@model IEnumerable<App_Data.Models.CartDetails>

@{
    IEnumerable<CartDetails> cartDetails = ViewBag.CartDetail;
    ViewData["Title"] = "ShowAllCartDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ShowAllCartDetail</h1>

<p>
    <a asp-action="AddCartDetail" asp-controller="CartDetail">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.IDUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDCTSP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaKhuyenMai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TrangThai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in cartDetails) {
        <tr>
            <td>
                @(item.IDUser)
            </td>
            <td>
                @( item.IDCTSP)
            </td>
            <td>
                @( item.SoLuong)
            </td>
            <td>
                @(item.GiaKhuyenMai)
            </td>
            <td>
                @(item.TrangThai)
            </td>
            <td>
               <a asp-controller="CartDetail" asp-action="EditCartDetail" asp-route-id="@item.ID">Sua</a>
                    <a asp-controller="CartDetail" asp-action="DetailCartDetail" asp-route-id="@item.ID">Chi Tiet</a>
                    <a asp-controller="CartDetail" asp-action="DeleteCartDetail" asp-route-id="@item.ID">Xoa</a>
            </td>
        </tr>
}
    </tbody>
</table>

App_View/Views/CartDetail/ShowCart.cshtml
@model IEnumerable<App_Data.ViewModel.CartViewModel>

@{
    Layout = "~/Views/Shared/_ProductsShop.cshtml";
}


<div class="container" style="margin-bottom:20px;color:black;">
    <div class="row ">
        <!-- =====  BANNER STRAT  ===== -->
        <!-- =====  BREADCRUMB END===== -->
        <div class="breadcrumb ptb_20">
            <h1>Giỏ hàng</h1>
            <ul>
                <li><a href="/">Home</a></li>
                <li class="active">Giỏ hàng</li>
            </ul>
        </div>

        <div class="col-sm col-lg mtb_20">
            <form enctype="multipart/form-data" method="post" action="#">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <td class="text-center">#</td>
                                <td class="text-left">Sản phẩm</td>
                                <td class="text-left">Thể loại</td>
                                <td class="text-left">Số lượng</td>
                                <td class="text-right">Giá bán</td>
                                <td class="text-right">Tổng giá</td>
                                <td class="text-right">Xóa</td>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                var total = item.GiaBan * item.SoLuongCart;
                                <tr data-row-id="{{@item.Id}}">
                                    <td class="text-center" style="margin-top: auto; margin-bottom: auto;">
                                        <img src="/images/anhsanpham/@item.LinkImage" class="img-fluid rounded-3"
                                             style="width: 44px;height: 39px;">
                                    </td>

                                    <td class="text-left" style="margin-top: auto; margin-bottom: auto;color:black"><a href="product.html">@Html.ActionLink(item.Name + "-" + item.Color + "-" + item.Size, "ChiTietSP", "Home", new { id = item.IdProduct })</a></td>

                                    <td class="text-left" style="margin-top: auto; margin-bottom: auto;">@item.Material</td>
                                    <td class="text-left" style="margin-top: auto; margin-bottom: auto">
                                        <div style="max-width: 100px;" class="input-group btn-block">
                                            <input type="number" min="0" name="quantity" value="@item.SoLuongCart" data-product-id="@item.IdProduct" data-cart-id="@item.Id" class="form-control soluong" size="1" style="color:black">
                                            <span class="input-group-btn">
                                            </span>
                                        </div>
                                    </td>
                                    <td class="text-right" style="margin-top: auto; margin-bottom: auto;">@string.Format("{0:N0}đ", item.GiaBan)</td>
                                    <td class="text-right" style="margin-top: auto; margin-bottom: auto;" id="tonggia">@string.Format("{0:N0}đ", item.GiaBan * item.SoLuongCart)</td>
                                    <td class="text-center" style="margin-top: auto; margin-bottom: auto;">
                                        @Html.ActionLink("Delete", "DeleteCartDetail", new { id = item.Id }, new { @class = "fa fa-trash color" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </form>

            @* <div class="panel-group mt_20" id="accordion">
                <div class="panel panel-default pull-left">
                    <div class="panel-heading">
                        <h4 class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Sử dụng mã giảm giá <i class="fa fa-caret-down"></i></a></h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <div class="input-group">
                                <input type="text" class="form-control" id="voucherinput" placeholder="Nhập phiếu giảm giá của bạn ở đây" name="voucher" oninput="voucher(this.value)">
                                <label id="textvoucher" style="color:red"></label>
                                <span class="input-group-btn">
                                    <input type="button" class="btn" data-loading-text="Loading..." id="button-coupon" value="Áp dụng" style="height: 38px;
                  border-radius: 5px;">
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div> *@
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8">
                    <table class="table table-bordered" style="border-block-color:black">
                        <tbody>
                            <tr>
                                <td class="text-right"><strong>Tổng giá:</strong></td>
                                <td class="text-right" id="tamtinh">@string.Format("{0:N0}đ", Model.Sum(x => x.SoLuongCart * x.GiaBan))</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Số tiền giảm:</strong></td>
                                <td class="text-right" id="giamgia">0đ</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Phí ship:</strong></td>
                                <td class="text-right">0đ</td>
                            </tr>
                            <tr>
                                <td class="text-right"><strong>Tổng:</strong></td>
                                <td class="text-right" id="tongtien">@string.Format("{0:N0}đ", Model.Sum(x => x.SoLuongCart * x.GiaBan))</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <form action="">
                <input class="btn pull-left mt_30" type="submit" value="Quay lại Shop" />
            </form>
            <a class="btn pull-right mt_30" href="/CartDetail/CheckOut" value="Thanh toán">

                thanh toán
            </a>

        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@section Scripts{
    <script>
        $(document).on("input", ".soluong", function () {
            updateCart(this);
        });

        $(document).on("click", ".soluong", function () {
            var inputElement = $(this);
            updateCart(inputElement);
        });

        function updateCart(inputElement) {
            var soLuong = parseInt($(inputElement).val());
            var IdProduct = $(inputElement).data('product-id');
            var idCart = $(inputElement).data('cart-id');

            $.ajax({
                url: '/CartDetail/CapNhatSoLuongGioHang',
                method: 'POST',
                data: { IdProduct: IdProduct, SoLuong: soLuong, idCart: idCart },
                success: function (response) {
                    // var inputs = document.getElementsByClassName('soluong');
                    // var sum = 0;
                    // for (var i = 0; i < inputs.length; i++) {
                    //     var inputValue = parseInt(inputs[i].value);
                    //     if (!isNaN(inputValue)) {
                    //         sum += inputValue;
                    //     }
                    // }
                    var TongTien = response.tongTien;
                    var TongGia = response.tongGia;
                    $('#tonggia').text(TongTien.toLocaleString("vi-VN") + "đ");
                    $('#tamtinh').text(TongTien.toLocaleString("vi-VN") + "đ");
                    $('#tongtien').text(TongTien.toLocaleString("vi-VN") + "đ");
                }
            });
        }
    </script>
    @* <script>
        var uudai = "";
        var tamtinh = document.getElementById("tamtinh").innerText.replace("đ", "").replace(/\,/g, "").replace(/\./g, "").trim();
        var tamtinhelement = parseInt(tamtinh);
        var tongtien = document.getElementById("tongtien");
        function voucher(value) {
            if (value != null && value.trim() != "") {
                var formData = new FormData();
                formData.append('Ma', value);
                $.ajax({
                    url: 'https://localhost:7165/api/Voucher/GetVoucherByMa?ma=' + value,
                    type: 'GET',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        console.log(result);
                        if (result) {
                            $('#giamgia').text("-" + result.MucUuDai.toLocaleString("vi-VN") + "đ");
                            $('#textvoucher').text("");
                            uudai = result.MucUuDai;
                            console.log(tamtinhelement);
                            var tong = tamtinhelement - uudai;
                            tongtien.innerText = tong.toLocaleString("vi-VN") + "đ";
                            tongtien.value = tong.toString();
                            // var totalAmountElement1 = document.getElementById("totalAmount1");
                            // totalAmountElement1.innerText = tongtien1.toLocaleString("vi-VN") + "đ";
                            // var paymentAmountElement = document.getElementById("paymentAmount");
                            // paymentAmountElement.innerText = tongtien1.toLocaleString("vi-VN") + "đ";

                            // var voucherValue = document.getElementById("voucherinput").value;
                            // document.getElementById("voucher1").value = voucherValue;
                        }
                        else {
                            $('#textvoucher').text("mã không hợp lệ");
                            $('#giamgia').text("0".toLocaleString("vi-VN") + "đ");
                            tongtien.innerText = tamtinhelement.toLocaleString("vi-VN") + "đ";
                            tongtien.value = tamtinhelement.toString();
                            // var totalAmountElement1 = document.getElementById("totalAmount1");
                            // totalAmountElement1.innerText = tongtien.toLocaleString("vi-VN") + "đ";
                            // var paymentAmountElement = document.getElementById("paymentAmount");
                            // paymentAmountElement.innerText = tongtien.toLocaleString("vi-VN") + "đ";

                            // var voucherValue = document.getElementById("voucherinput").value;
                            // document.getElementById("voucher1").value = "Vouc11";
                        }
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr.responseText);
                        console.log(status);
                        console.log(error);
                        console.log(xhr);
                    }
                });
            } else {
                tongtien.innerText = tamtinhelement.toLocaleString("vi-VN") + "đ";
                tongtien.value = tamtinhelement.toString();
                $('#giamgia').text("0".toLocaleString("vi-VN") + "đ");
                $('#textvoucher').text("");
            }


        }
    </script> *@
}